version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "8083:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_DEFAULT_EMAIL: "alvvar055@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1q2w"

volumes:
  postgres_data:
